name: Workflow 1

on:
  workflow_dispatch:

jobs:
  test_actions:
    name: Testing custom composite action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run the custom action
        uses: actions/composite-action-1
        with:
          name: 'Moo'

      - run: echo "Done workflow"
        shell: bash
