name: Workflow 1

on:
  workflow_dispatch:

jobs:
  test_actions:
    name: Testing custom composite action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run the custom action
        uses: ./.github/actions/composite-action-1
        with:
          name: 'Moo'

      - name: Run stand-alone custom action
        uses: jabrah/my-custom-action@v0.1.0
        with:
          name: 'Lorem ipsum'

      - run: echo "Done workflow"
        shell: bash
